// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'ORMconfiguration.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Phone.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// Phone TABLE
class TablePhone extends SqfEntityTableBase {
  TablePhone() {
    // declare properties of EntityTable
    tableName = 'Phones';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('producer', DbType.text),
      SqfEntityFieldBase('phoneModel', DbType.text),
      SqfEntityFieldBase('androidVersion', DbType.real),
      SqfEntityFieldBase('phoneWebPage', DbType.text),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TablePhone();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class MyDbModel extends SqfEntityModelProvider {
  MyDbModel() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;

    databaseTables = [
      TablePhone.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};
    controllers['phones'] = PhoneController.getController;

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Phone
class Phone {
  Phone(
      {this.id,
      this.producer,
      this.phoneModel,
      this.androidVersion,
      this.phoneWebPage}) {
    _setDefaultValues();
  }
  Phone.withFields(
      this.producer, this.phoneModel, this.androidVersion, this.phoneWebPage) {
    _setDefaultValues();
  }
  Phone.withId(id, this.producer, this.phoneModel, this.androidVersion,
      this.phoneWebPage) {
    _setDefaultValues();
  }
  Phone.fromMap(Map<String, dynamic> o) {
    _setDefaultValues();
    id = int.tryParse(o['id'].toString());
    if (o['producer'] != null) producer = o['producer'] as String;
    if (o['phoneModel'] != null) phoneModel = o['phoneModel'] as String;
    if (o['androidVersion'] != null)
      androidVersion = double.tryParse(o['androidVersion'].toString());
    if (o['phoneWebPage'] != null) phoneWebPage = o['phoneWebPage'] as String;
  }
  // FIELDS (Phone)
  int id;
  String producer;
  String phoneModel;
  double androidVersion;
  String phoneWebPage;

  BoolResult saveResult;
  // end FIELDS (Phone)

  static const bool _softDeleteActivated = false;
  PhoneManager __mnPhone;

  PhoneManager get _mnPhone {
    return __mnPhone = __mnPhone ?? PhoneManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (producer != null) {
      map['producer'] = producer;
    }

    if (phoneModel != null) {
      map['phoneModel'] = phoneModel;
    }

    if (androidVersion != null) {
      map['androidVersion'] = androidVersion;
    }

    if (phoneWebPage != null) {
      map['phoneWebPage'] = phoneWebPage;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChilds(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (producer != null) {
      map['producer'] = producer;
    }

    if (phoneModel != null) {
      map['phoneModel'] = phoneModel;
    }

    if (androidVersion != null) {
      map['androidVersion'] = androidVersion;
    }

    if (phoneWebPage != null) {
      map['phoneWebPage'] = phoneWebPage;
    }

    return map;
  }

  /// This method returns Json String
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChilds(false, true));
  }

  List<dynamic> toArgs() {
    return [producer, phoneModel, androidVersion, phoneWebPage];
  }

  List<dynamic> toArgsWithIds() {
    return [id, producer, phoneModel, androidVersion, phoneWebPage];
  }

  static Future<List<Phone>> fromWebUrl(String url) async {
    try {
      final response = await http.get(url);
      return await fromJson(response.body);
    } catch (e) {
      print('SQFENTITY ERROR Phone.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  static Future<List<Phone>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Phone>[];
    try {
      objList = list
          .map((phone) => Phone.fromMap(phone as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Phone.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  /*
    /// REMOVED AFTER v1.2.1+14 
    static Future<List<Phone>> fromObjectList(Future<List<dynamic>> o) async {
      final data = await o;
      return await Phone.fromMapList(data);
    } 
    */

  static Future<List<Phone>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final List<Phone> objList = <Phone>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Phone.fromMap(map as Map<String, dynamic>);
      final List<String> _loadedFields = List<String>.from(loadedFields);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Phone by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Phone if exist, otherwise returns null
  Future<Phone> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    Phone obj;
    final data = await _mnPhone.getById([id]);
    if (data.length != 0) {
      obj = Phone.fromMap(data[0] as Map<String, dynamic>);
      final List<String> _loadedFields = loadedFields ?? [];
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Phone) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnPhone.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnPhone.update(this);
    }

    return id;
  }

  /// saveAs Phone. Returns a new Primary Key value of Phone

  /// <returns>Returns a new Primary Key value of Phone
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Phone> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  Future<List<dynamic>> saveAll(List<Phone> phones) async {
    // final results = _mnPhone.saveAll('INSERT OR REPLACE INTO Phones (id,producer, phoneModel, androidVersion, phoneWebPage)  VALUES (?,?,?,?,?)',phones);
    // return results; removed in sqfentity_gen 1.3.0+6
    MyDbModel().batchStart();
    for (final obj in phones) {
      await obj.save();
    }
    return MyDbModel().batchCommit();
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnPhone.rawInsert(
              'INSERT OR REPLACE INTO Phones (id,producer, phoneModel, androidVersion, phoneWebPage)  VALUES (?,?,?,?,?)',
              [id, producer, phoneModel, androidVersion, phoneWebPage]) ==
          1) {
        saveResult = BoolResult(
            success: true, successMessage: 'Phone id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Phone id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Phone Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Phone>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<Phone> phones) async {
    final results = await _mnPhone.rawInsertAll(
        'INSERT OR REPLACE INTO Phones (id,producer, phoneModel, androidVersion, phoneWebPage)  VALUES (?,?,?,?,?)',
        phones);
    return results;
  }

  /// Deletes Phone

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Phone invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnPhone
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnPhone.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  //private PhoneFilterBuilder _Select;
  PhoneFilterBuilder select({List<String> columnsToSelect, bool getIsDeleted}) {
    return PhoneFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  PhoneFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return PhoneFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {}
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion phone

// region PhoneField
class PhoneField extends SearchCriteria {
  PhoneField(this.phoneFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  PhoneFilterBuilder phoneFB;

  PhoneField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  PhoneFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    phoneFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, phoneFB.parameters, param, SqlSyntax.EQuals,
            phoneFB._addedBlocks)
        : setCriteria(pValue, phoneFB.parameters, param, SqlSyntax.NotEQuals,
            phoneFB._addedBlocks);
    _waitingNot = '';
    phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
        phoneFB._addedBlocks.retVal;
    return phoneFB;
  }

  PhoneFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    phoneFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, phoneFB.parameters, param, SqlSyntax.EQualsOrNull,
            phoneFB._addedBlocks)
        : setCriteria(pValue, phoneFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, phoneFB._addedBlocks);
    _waitingNot = '';
    phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
        phoneFB._addedBlocks.retVal;
    return phoneFB;
  }

  PhoneFilterBuilder isNull() {
    phoneFB._addedBlocks = setCriteria(
        0,
        phoneFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        phoneFB._addedBlocks);
    _waitingNot = '';
    phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
        phoneFB._addedBlocks.retVal;
    return phoneFB;
  }

  PhoneFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      phoneFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          phoneFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          phoneFB._addedBlocks);
      _waitingNot = '';
      phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
          phoneFB._addedBlocks.retVal;
    }
    return phoneFB;
  }

  PhoneFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      phoneFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          phoneFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          phoneFB._addedBlocks);
      _waitingNot = '';
      phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
          phoneFB._addedBlocks.retVal;
      phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
          phoneFB._addedBlocks.retVal;
    }
    return phoneFB;
  }

  PhoneFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      phoneFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          phoneFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          phoneFB._addedBlocks);
      _waitingNot = '';
      phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
          phoneFB._addedBlocks.retVal;
    }
    return phoneFB;
  }

  PhoneFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      phoneFB._addedBlocks = setCriteria(
          pFirst,
          phoneFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          phoneFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        phoneFB._addedBlocks = setCriteria(pFirst, phoneFB.parameters, param,
            SqlSyntax.LessThan, phoneFB._addedBlocks);
      } else {
        phoneFB._addedBlocks = setCriteria(pFirst, phoneFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, phoneFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        phoneFB._addedBlocks = setCriteria(pLast, phoneFB.parameters, param,
            SqlSyntax.GreaterThan, phoneFB._addedBlocks);
      } else {
        phoneFB._addedBlocks = setCriteria(pLast, phoneFB.parameters, param,
            SqlSyntax.LessThanOrEquals, phoneFB._addedBlocks);
      }
    }
    _waitingNot = '';
    phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
        phoneFB._addedBlocks.retVal;
    return phoneFB;
  }

  PhoneFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    phoneFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, phoneFB.parameters, param, SqlSyntax.GreaterThan,
            phoneFB._addedBlocks)
        : setCriteria(pValue, phoneFB.parameters, param,
            SqlSyntax.LessThanOrEquals, phoneFB._addedBlocks);
    _waitingNot = '';
    phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
        phoneFB._addedBlocks.retVal;
    return phoneFB;
  }

  PhoneFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    phoneFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, phoneFB.parameters, param, SqlSyntax.LessThan,
            phoneFB._addedBlocks)
        : setCriteria(pValue, phoneFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, phoneFB._addedBlocks);
    _waitingNot = '';
    phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
        phoneFB._addedBlocks.retVal;
    return phoneFB;
  }

  PhoneFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    phoneFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, phoneFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, phoneFB._addedBlocks)
        : setCriteria(pValue, phoneFB.parameters, param, SqlSyntax.LessThan,
            phoneFB._addedBlocks);
    _waitingNot = '';
    phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
        phoneFB._addedBlocks.retVal;
    return phoneFB;
  }

  PhoneFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    phoneFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, phoneFB.parameters, param,
            SqlSyntax.LessThanOrEquals, phoneFB._addedBlocks)
        : setCriteria(pValue, phoneFB.parameters, param, SqlSyntax.GreaterThan,
            phoneFB._addedBlocks);
    _waitingNot = '';
    phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
        phoneFB._addedBlocks.retVal;
    return phoneFB;
  }

  PhoneFilterBuilder inValues(dynamic pValue) {
    phoneFB._addedBlocks = setCriteria(
        pValue,
        phoneFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        phoneFB._addedBlocks);
    _waitingNot = '';
    phoneFB._addedBlocks.needEndBlock[phoneFB._blockIndex] =
        phoneFB._addedBlocks.retVal;
    return phoneFB;
  }
}
// endregion PhoneField

// region PhoneFilterBuilder
class PhoneFilterBuilder extends SearchCriteria {
  PhoneFilterBuilder(Phone obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Phone _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  PhoneFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  PhoneFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  PhoneFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  PhoneFilterBuilder where(String whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param =
          DbParameter(columnName: parameterValue == null ? null : '');
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  PhoneFilterBuilder page(int page, int pagesize) {
    if (page > 0) _page = page;
    if (pagesize > 0) _pagesize = pagesize;
    return this;
  }

  /// int count = LIMIT
  PhoneFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  PhoneFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  PhoneFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') orderByList.add(' $s ');
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  PhoneFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') orderByList.add(' $s desc ');
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  PhoneFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') groupByList.add(' $s ');
        }
      }
    }
    return this;
  }

  PhoneField setField(PhoneField field, String colName, DbType dbtype) {
    return PhoneField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  PhoneField _id;
  PhoneField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  PhoneField _producer;
  PhoneField get producer {
    return _producer = setField(_producer, 'producer', DbType.text);
  }

  PhoneField _phoneModel;
  PhoneField get phoneModel {
    return _phoneModel = setField(_phoneModel, 'phoneModel', DbType.text);
  }

  PhoneField _androidVersion;
  PhoneField get androidVersion {
    return _androidVersion =
        setField(_androidVersion, 'androidVersion', DbType.real);
  }

  PhoneField _phoneWebPage;
  PhoneField get phoneWebPage {
    return _phoneWebPage = setField(_phoneWebPage, 'phoneWebPage', DbType.text);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List) {
          param.value = param.value
              .toString()
              .replaceAll('[', '')
              .replaceAll(']', '')
              .toString();
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            whereArguments.add(param.value);
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Phone._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',');
  }

  /// Deletes List<Phone> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (Phone._softDeleteActivated && !hardDelete) {
      r = await _obj._mnPhone.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnPhone.delete(qparams);
    }
    return r;
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from Phones ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnPhone.updateBatch(qparams, values);
  }

  /// This method always returns Phone Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Phone>
  Future<Phone> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnPhone.toList(qparams);
    final data = await objFuture;
    Phone obj;
    if (data.isNotEmpty) {
      obj = Phone.fromMap(data[0] as Map<String, dynamic>);
      final List<String> _loadedFields = loadedFields ?? [];
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int.
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) phoneCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final phonesFuture = await _obj._mnPhone.toList(qparams);
    final int count = phonesFuture[0]['CNT'] as int;
    if (phoneCount != null) {
      phoneCount(count);
    }
    return count;
  }

  /// This method returns List<Phone>.
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Phone>
  Future<List<Phone>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<Phone> phonesData = await Phone.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields);
    return phonesData;
  }

  /// This method returns Json String
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String.
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChilds(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>.
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnPhone.toList(qparams);
  }

  /// Returns List<DropdownMenuItem<Phone>>
  Future<List<DropdownMenuItem<Phone>>> toDropDownMenu(String displayTextColumn,
      [VoidCallback Function(List<DropdownMenuItem<Phone>> o)
          dropDownMenu]) async {
    _buildParameters();
    final phonesFuture = _obj._mnPhone.toList(qparams);

    final data = await phonesFuture;
    final int count = data.length;
    final List<DropdownMenuItem<Phone>> items = []..add(DropdownMenuItem(
        value: Phone(),
        child: Text('Select Phone'),
      ));
    for (int i = 0; i < count; i++) {
      items.add(
        DropdownMenuItem(
          value: Phone.fromMap(data[i] as Map<String, dynamic>),
          child: Text(data[i][displayTextColumn].toString()),
        ),
      );
    }
    if (dropDownMenu != null) {
      dropDownMenu(items);
    }
    return items;
  }

  /// Returns List<DropdownMenuItem<int>>
  Future<List<DropdownMenuItem<int>>> toDropDownMenuInt(
      String displayTextColumn,
      [VoidCallback Function(List<DropdownMenuItem<int>> o)
          dropDownMenu]) async {
    _buildParameters();
    qparams.selectColumns = ['id', displayTextColumn];
    final phonesFuture = _obj._mnPhone.toList(qparams);

    final data = await phonesFuture;
    final int count = data.length;
    final List<DropdownMenuItem<int>> items = []..add(DropdownMenuItem(
        value: 0,
        child: Text('Select Phone'),
      ));
    for (int i = 0; i < count; i++) {
      items.add(
        DropdownMenuItem(
          value: data[i]['id'] as int,
          child: Text(data[i][displayTextColumn].toString()),
        ),
      );
    }
    if (dropDownMenu != null) {
      dropDownMenu(items);
    }
    return items;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) _buildParameters();
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnPhone.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnPhone.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Phone.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnPhone.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion PhoneFilterBuilder

// region PhoneFields
class PhoneFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fProducer;
  static TableField get producer {
    return _fProducer =
        _fProducer ?? SqlSyntax.setField(_fProducer, 'producer', DbType.text);
  }

  static TableField _fPhoneModel;
  static TableField get phoneModel {
    return _fPhoneModel = _fPhoneModel ??
        SqlSyntax.setField(_fPhoneModel, 'phoneModel', DbType.text);
  }

  static TableField _fAndroidVersion;
  static TableField get androidVersion {
    return _fAndroidVersion = _fAndroidVersion ??
        SqlSyntax.setField(_fAndroidVersion, 'androidVersion', DbType.real);
  }

  static TableField _fPhoneWebPage;
  static TableField get phoneWebPage {
    return _fPhoneWebPage = _fPhoneWebPage ??
        SqlSyntax.setField(_fPhoneWebPage, 'phoneWebPage', DbType.text);
  }
}
// endregion PhoneFields

//region PhoneManager
class PhoneManager extends SqfEntityProvider {
  PhoneManager()
      : super(MyDbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static String _tableName = 'Phones';
  //static String _colId = 'id';
  static List<String> _primaryKeyList = ['id'];
  static String _whereStr = 'id=?';
}

//endregion PhoneManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o) nextval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o) currentval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o) currentval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class MyDbModelSequenceManager extends SqfEntityProvider {
  MyDbModelSequenceManager() : super(MyDbModel());
}
// END OF ENTITIES

// BEGIN CONTROLLERS
// BEGIN CONTROLLER (Phone)

class PhoneController extends Phone {
  String formListTitleField = 'producer';
  String formListSubTitleField = 'phoneModel';
  static SQFViewList getController = SQFViewList(
    PhoneController(),
    primaryKeyName: 'id',
    useSoftDeleting: false,
  );
  Map<String, String> subMenu() {
    final menu = <String, String>{};

    return menu;
  }

  Future<Widget> gotoEdit(dynamic obj) async {
    return PhoneAdd(obj == null
        ? Phone()
        : await Phone().getById(obj['id'] as int) ?? Phone());
  }
}
// END CONTROLLER (Phone)

// END OF CONTROLLERS
